### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by impressivewebs** [perfectnote/web#2]
https://perfectnote.org/

Doesn't work...?

**Comment by aidenybai** [comment]
Hey Louis, thanks for the heads up. Our project is currently in the development phase and we haven't pushed a release yet, therefore not having any content on our website _currently_. You can view our progress on discord if you want to keep updated: https://discord.gg/nTfPcBZ

**Comment by impressivewebs** [comment]
Ah ok, no problem. Was just curious since the URL was listed in the repo.

**Comment by aidenybai** [comment]
Cool, thanks for the heads up and your interest in perfectnote!
